name: "Test workflow_call"

on:
  workflow_dispatch:
    inputs:
      remove_git_hooks:
        description: "Remove Git Hooks"
        type: boolean
        required: false
        default: true
      unos_debug:
        description: "Enable debug logging"
        type: boolean
        required: false
        default: true
      unos_test_mode:
        description: "Enable test mode"
        type: boolean
        required: false
        default: true
      unos_min_major_os_version:
        description: "Minimum Major OS version supported"
        type: string
        required: false
      unos_nudge_json_file:
        description: "Path to your Nudge JSON file"
        type: string
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  call_update_nudge_version:
    # uses: ./.github/workflows/update-nudge-version.yml
    uses: smithjw/nudge-actions/.github/workflows/update-nudge-version.yml@d3a13bae9fbbd9a6ab08532f31502677539eb7e6 # v0.3.0
    with:
      remove_git_hooks: ${{ inputs.remove_git_hooks }}
      unos_debug: ${{ inputs.unos_debug }}
      unos_test_mode: ${{ inputs.unos_test_mode }}
      unos_min_major_os_version: ${{ inputs.unos_min_major_os_version }}
      unos_nudge_json_file: ${{ inputs.unos_nudge_json_file }}
