name: "Update Nudge osVersionRequirements"

on:
  workflow_dispatch:
    inputs:
      unos_debug:
        description: "Enable debug logging"
        type: boolean
        required: false
        default: true
      unos_test_mode:
        description: "Enable test mode"
        type: boolean
        required: false
        default: true
      unos_min_major_os_version:
        description: "Minimum Major OS version supported"
        type: string
        required: false
      unos_nudge_json_file:
        description: "Path to your Nudge JSON file"
        type: string
        required: false
  workflow_call:
    inputs:
      unos_debug:
        description: "Enable debug logging"
        type: boolean
        required: false
        default: true
      unos_test_mode:
        description: "Enable test mode"
        type: boolean
        required: false
        default: true
      unos_min_major_os_version:
        description: "Minimum Major OS version supported"
        type: string
        required: false
      unos_nudge_json_file:
        description: "Path to your Nudge JSON file"
        type: string
        required: false

permissions:
  contents: read

jobs:
  update_nudge_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Nudge-Action Repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: smithjw/nudge-actions
          path: nudge-actions

      - name: Extract Python version from .tool-versions file
        id: extract_version
        env:
          tool_name: python
        run: |
          version=$(awk -v name="$tool_name" '$1 == name {print $2}' nudge-actions/.tool-versions)
          echo "PYTHON_VERSION=${version:=latest}" >> $GITHUB_OUTPUT

      - name: Install Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: ${{ steps.extract_version.outputs.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'nudge-actions/app/requirements.txt'

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r nudge-actions/app/requirements.txt --require-hashes

      - name: Run Nudge-Action
        env:
          UNOS_DEBUG: ${{ inputs.UNOS_DEBUG }}
          UNOS_TEST_MODE: ${{ inputs.unos_test_mode }}
          UNOS_MIN_MAJOR_OS_VERSION: ${{ inputs.UNOS_MIN_MAJOR_OS_VERSION }}
          UNOS_NUDGE_JSON_FILE: ${{ inputs.UNOS_NUDGE_JSON_FILE }}
        run: |
          source .venv/bin/activate
          python nudge-actions/app/update_nudge_osVersionRequirements.py
