name: "Update Nudge osVersionRequirements"

on:
  workflow_dispatch:
    inputs:
      remove_git_hooks:
        description: "Remove Git Hooks"
        type: boolean
        required: false
        default: true
      unos_debug:
        description: "Enable debug logging"
        type: boolean
        required: false
        default: true
      unos_test_mode:
        description: "Enable test mode"
        type: boolean
        required: false
        default: true
      unos_min_major_os_version:
        description: "Minimum Major OS version supported"
        type: string
        required: false
      unos_nudge_json_file:
        description: "Path to your Nudge JSON file"
        type: string
        required: false
        default: "nudge.json"
  workflow_call:
    inputs:
      remove_git_hooks:
        description: "Remove Git Hooks"
        type: boolean
        required: false
        default: true
      unos_debug:
        description: "Enable debug logging"
        type: boolean
        required: false
        default: true
      unos_test_mode:
        description: "Enable test mode"
        type: boolean
        required: false
        default: true
      unos_min_major_os_version:
        description: "Minimum Major OS version supported"
        type: string
        required: false
      unos_nudge_json_file:
        description: "Path to your Nudge JSON file"
        type: string
        required: false
        default: "nudge.json"

permissions:
  contents: write
  pull-requests: write

jobs:
  update_nudge_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Caller Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Checkout Nudge-Actions Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: smithjw/nudge-actions
          path: nudge-actions

      - name: Extract Python version from .tool-versions file
        id: extract_version
        env:
          tool_name: python
        run: |
          version=$(awk -v name="$tool_name" '$1 == name {print $2}' nudge-actions/.tool-versions)
          echo "PYTHON_VERSION=${version:=latest}" >> $GITHUB_OUTPUT

      - name: Install Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: ${{ steps.extract_version.outputs.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'nudge-actions/app/requirements.txt'

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r nudge-actions/app/requirements.txt --require-hashes

      - name: Run Nudge-Action
        env:
          UNOS_DEBUG: ${{ inputs.unos_debug }}
          UNOS_TEST_MODE: ${{ inputs.unos_test_mode }}
          UNOS_MIN_MAJOR_OS_VERSION: ${{ inputs.unos_min_major_os_version }}
          UNOS_NUDGE_JSON_FILE: ${{ inputs.unos_nudge_json_file }}
        run: |
          source .venv/bin/activate
          python nudge-actions/app/update_nudge_osVersionRequirements.py

      - name: Remove git hooks
        if: inputs.remove_git_hooks
        run: |
          rm -rf .git/hooks

      - name: Remove smithjw/nudge-actions
        run: |
          rm -rf nudge-actions

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          branch: update-nudge-osVersionRequirements
          commit-message: "Update ${{ inputs.unos_nudge_json_file }} with latest macOS versions"
          title: "Update to Nudge osVersionRequirements"
          body: "A new version of macOS has been released, please review the changes and merge this PR to update the Nudge osVersionRequirements key"
          add-paths: |
            ${{ inputs.unos_nudge_json_file }}
